# Generated by Django 3.0.9 on 2023-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('loan_type_id', models.PositiveIntegerField()),
                ('loan_amount', models.PositiveIntegerField()),
                ('interest_rate', models.FloatField()),
                ('term_period', models.PositiveIntegerField()),
                ('disbursement_date', models.DateField()),
                ('is_active', models.BooleanField(null=True)),
                ('remaining_amount', models.PositiveIntegerField(null=True)),
                ('remaining_period', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=25)),
                ('max_approved_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('loan', models.PositiveIntegerField()),
                ('amount_paid', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
