# Generated by Django 3.0.9 on 2023-09-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20230909_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='max_approved_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_paid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remaining_amount',
            field=models.FloatField(null=True),
        ),
    ]
